arc:
  ai:
    clients:
      - id: GPT-4o
        model-name: GPT35T-1106
        api-key: dummy
        client: azure
        url: https://gpt4-uk.openai.azure.com

wot:
  servient:
    security:
      credentials:
        "[https://plugfest.webthings.io]":
          type: "bearer"
          token: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjE1OWM4MzhlLWYxZmItNGE3ZC1iZDY2LTBlNmI1ZDZjNWVhMCJ9.eyJyb2xlIjoidXNlcl90b2tlbiIsImlhdCI6MTczMjI5MjczNSwiaXNzIjoiaHR0cHM6Ly9wbHVnZmVzdC53ZWJ0aGluZ3MuaW8ifQ.CpQ5MLSygmCJFS6yz4Xdf0xyImwqBWvNfKNZPX9DNHjyjuq5wzq0mWurSu11wR-BwnZ2lnFcIId3ytfbo9hBwg"
    websocket:
      server:
        enabled: true
        host: localhost
        port: 8181
    http:
      server:
        enabled: true
        host: localhost
        port: 8080
        baseUrls:
          - http://localhost:8080
          - http://not-existing-external-url:8080
    mqtt:
      server:
        enabled: false
        host: localhost
        port: 54801
        clientId: wot-servient
      client:
        enabled: false
        host: localhost
        port: 54801
        clientId: wot-client
